# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read an Enconded File, Optionally Converting to Another Encoding
#'
#' This function relies on the 'iconv' facility available with R. Having 'iconv' is optional but
#' likely for most builds of R; see \code{capabilities("iconv")} to verify. Also note that
#' 'iconv', while portable, does not guarantee identical results across implementations and
#' operating systems.
#'
#' @param filename [string] A filename
#' @param encoding [string, optional] An encoding. If present, file content is converted
#' to the given encoding; if missing (as indicated by the default empty string) no conversion
#' is made.
#' @return A string
#' @seealso https://fishandwhistle.net/post/2021/using-rs-cross-platform-iconv-wrapper-from-cpp11/
#' @examples
#' ## example file from package 'uchardet' encoding as windows-1252
#' win1252file <- system.file("rawdata", "windows-1252.txt", package="RcppIconvExample")
#' win1252txt <- read_file(win1252file, "windows-1252")
#' utf8file <- system.file("rawdata", "utf8.txt", package="RcppIconvExample")
#' utf8txt <- read_file(utf8file, "UTF-8")
#' stopifnot(substr(win1252txt, 1, 62) == substr(utf8txt, 1, 62))
#' cat(win1252txt)
read_file <- function(filename, encoding = "") {
    .Call(`_RcppIconvExample_read_file`, filename, encoding)
}

